default: &default
  adapter: postgresql
  encoding: utf-8
  username: admin
  password: 123456
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: handyCMS_development

test:
  <<: *default
  database: handyCMS_test

production:
  <<: *default
  database: handyCMS_production
  username: handyCMS
  password: <%= ENV['HANDYCMS_DATABASE_PASSWORD'] %>
